{
  "hash": "f0ebc2ccfe3854d7d5176641a0011924",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Gab Chen\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(sf)\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(tigris)\nlibrary(tidycensus)\n\n# Load spatial data\npa_counties <- st_read(\"C:/Users/Gab/OneDrive/Documents/SPRING 2026/CPLN5920_PPA/PPA_Portfolio/lecture/week4/Pennsylvania_County_Boundaries/Pennsylvania_County_Boundaries.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Pennsylvania_County_Boundaries' from data source \n  `C:\\Users\\Gab\\OneDrive\\Documents\\SPRING 2026\\CPLN5920_PPA\\PPA_Portfolio\\lecture\\week4\\Pennsylvania_County_Boundaries\\Pennsylvania_County_Boundaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals <- st_read(\"C:/Users/Gab/OneDrive/Documents/SPRING 2026/CPLN5920_PPA/PPA_Portfolio/lecture/week4/hospitals.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hospitals' from data source \n  `C:\\Users\\Gab\\OneDrive\\Documents\\SPRING 2026\\CPLN5920_PPA\\PPA_Portfolio\\lecture\\week4\\hospitals.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\npa_tracts <- tracts(\n  state = \"PA\",\n  cb = TRUE,\n  year = 2022\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |                                                                      |   1%\n  |                                                                            \n  |=                                                                     |   2%\n  |                                                                            \n  |==                                                                    |   2%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |====                                                                  |   5%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |======                                                                |   8%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |=======                                                               |  11%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |===========                                                           |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |=============                                                         |  18%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |===============                                                       |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |==================                                                    |  25%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |====================                                                  |  28%\n  |                                                                            \n  |====================                                                  |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |======================                                                |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |========================                                              |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |==========================                                            |  38%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |=============================                                         |  41%\n  |                                                                            \n  |=============================                                         |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |===============================                                       |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |=================================                                     |  48%\n  |                                                                            \n  |==================================                                    |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |===================================                                   |  51%\n  |                                                                            \n  |====================================                                  |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |=====================================                                 |  54%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |=======================================                               |  55%\n  |                                                                            \n  |========================================                              |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |=========================================                             |  58%\n  |                                                                            \n  |==========================================                            |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |============================================                          |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |==============================================                        |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |================================================                      |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |==================================================                    |  71%\n  |                                                                            \n  |===================================================                   |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |=====================================================                 |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |=======================================================               |  78%\n  |                                                                            \n  |=======================================================               |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |=========================================================             |  82%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |===========================================================           |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |=============================================================         |  88%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |================================================================      |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |==================================================================    |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |====================================================================  |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check that all data loaded correctly\nglimpse(hospitals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 223\nColumns: 12\n$ CHIEF_EXEC <chr> \"Peter J Adamo\", \"Autumn DeShields\", \"Shawn Parekh\", \"DIANE…\n$ CHIEF_EX_1 <chr> \"President\", \"Chief Executive Officer\", \"Chief Executive Of…\n$ FACILITY_U <chr> \"https://www.phhealthcare.org\", \"https://www.malvernbh.com\"…\n$ LONGITUDE  <dbl> -79.91131, -75.17005, -75.20963, -80.27907, -79.02513, -75.…\n$ COUNTY     <chr> \"Washington\", \"Philadelphia\", \"Philadelphia\", \"Washington\",…\n$ FACILITY_N <chr> \"Penn Highlands Mon Valley\", \"MALVERN BEHAVIORAL HEALTH\", \"…\n$ STREET     <chr> \"1163 Country Club Road\", \"1930 South Broad Street Unit 4\",…\n$ CITY_OR_BO <chr> \"Monongahela\", \"Philadelphia\", \"Philadelphia\", \"WASHINGTON\"…\n$ LATITUDE   <dbl> 40.18193, 39.92619, 40.02869, 40.15655, 39.80913, 40.24273,…\n$ TELEPHONE_ <chr> \"724-258-1000\", \"610-480-8919\", \"215-483-9900\", \"7248840710…\n$ ZIP_CODE   <chr> \"15063\", \"19145\", \"19128\", \"15301\", \"15552\", \"19464\", \"1776…\n$ geometry   <POINT [°]> POINT (-79.91131 40.18193), POINT (-75.17005 39.9262)…\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(pa_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 3,445\nColumns: 14\n$ STATEFP    <chr> \"42\", \"42\", \"42\", \"42\", \"42\", \"42\", \"42\", \"42\", \"42\", \"42\",…\n$ COUNTYFP   <chr> \"001\", \"013\", \"013\", \"013\", \"011\", \"011\", \"011\", \"011\", \"01…\n$ TRACTCE    <chr> \"031101\", \"100400\", \"100300\", \"100800\", \"000100\", \"012200\",…\n$ AFFGEOID   <chr> \"1400000US42001031101\", \"1400000US42013100400\", \"1400000US4…\n$ GEOID      <chr> \"42001031101\", \"42013100400\", \"42013100300\", \"42013100800\",…\n$ NAME       <chr> \"311.01\", \"1004\", \"1003\", \"1008\", \"1\", \"122\", \"133.02\", \"13…\n$ NAMELSAD   <chr> \"Census Tract 311.01\", \"Census Tract 1004\", \"Census Tract 1…\n$ STUSPS     <chr> \"PA\", \"PA\", \"PA\", \"PA\", \"PA\", \"PA\", \"PA\", \"PA\", \"PA\", \"PA\",…\n$ NAMELSADCO <chr> \"Adams County\", \"Blair County\", \"Blair County\", \"Blair Coun…\n$ STATE_NAME <chr> \"Pennsylvania\", \"Pennsylvania\", \"Pennsylvania\", \"Pennsylvan…\n$ LSAD       <chr> \"CT\", \"CT\", \"CT\", \"CT\", \"CT\", \"CT\", \"CT\", \"CT\", \"CT\", \"CT\",…\n$ ALAND      <dbl> 3042633, 993724, 1217046, 996553, 807871, 2788188, 39133067…\n$ AWATER     <dbl> 0, 0, 0, 0, 0, 30830, 137739, 128147, 0, 0, 35788, 0, 1271,…\n$ geometry   <MULTIPOLYGON [°]> MULTIPOLYGON (((-77.03108 3..., MULTIPOLYGON (…\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(pa_counties)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 67\nColumns: 20\n$ OBJECTID   <int> 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347,…\n$ MSLINK     <int> 46, 8, 9, 58, 59, 60, 62, 63, 42, 43, 44, 47, 48, 49, 50, 5…\n$ COUNTY_NAM <chr> \"MONTGOMERY\", \"BRADFORD\", \"BUCKS\", \"TIOGA\", \"UNION\", \"VENAN…\n$ COUNTY_NUM <chr> \"46\", \"08\", \"09\", \"58\", \"59\", \"60\", \"62\", \"63\", \"42\", \"43\",…\n$ FIPS_COUNT <chr> \"091\", \"015\", \"017\", \"117\", \"119\", \"121\", \"125\", \"127\", \"08…\n$ COUNTY_ARE <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ COUNTY_PER <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ NUMERIC_LA <int> 5, 2, 5, 2, 2, 3, 1, 2, 1, 3, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1,…\n$ COUNTY_N_1 <int> 46, 8, 9, 58, 59, 60, 62, 63, 42, 43, 44, 47, 48, 49, 50, 5…\n$ AREA_SQ_MI <dbl> 487.4271, 1161.3379, 622.0836, 1137.2480, 319.1893, 683.367…\n$ SOUND      <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ SPREAD_SHE <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ IMAGE_NAME <chr> \"poll.bmp\", \"poll.bmp\", \"poll.bmp\", \"poll.bmp\", \"poll.bmp\",…\n$ NOTE_FILE  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ VIDEO      <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ DISTRICT_N <chr> \"06\", \"03\", \"06\", \"03\", \"03\", \"01\", \"12\", \"04\", \"02\", \"01\",…\n$ PA_CTY_COD <chr> \"46\", \"08\", \"09\", \"59\", \"60\", \"61\", \"63\", \"64\", \"42\", \"43\",…\n$ MAINT_CTY_ <chr> \"4\", \"9\", \"1\", \"7\", \"8\", \"5\", \"4\", \"6\", \"5\", \"4\", \"7\", \"3\",…\n$ DISTRICT_O <chr> \"6-4\", \"3-9\", \"6-1\", \"3-7\", \"3-8\", \"1-5\", \"12-4\", \"4-6\", \"2…\n$ geometry   <MULTIPOLYGON [m]> MULTIPOLYGON (((-8398884 48..., MULTIPOLYGON (…\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check crs\nst_crs(hospitals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(pa_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: NAD83 \n  wkt:\nGEOGCRS[\"NAD83\",\n    DATUM[\"North American Datum 1983\",\n        ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"latitude\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"longitude\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4269]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(pa_counties)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 / Pseudo-Mercator \n  wkt:\nPROJCRS[\"WGS 84 / Pseudo-Mercator\",\n    BASEGEOGCRS[\"WGS 84\",\n        ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n            MEMBER[\"World Geodetic System 1984 (Transit)\"],\n            MEMBER[\"World Geodetic System 1984 (G730)\"],\n            MEMBER[\"World Geodetic System 1984 (G873)\"],\n            MEMBER[\"World Geodetic System 1984 (G1150)\"],\n            MEMBER[\"World Geodetic System 1984 (G1674)\"],\n            MEMBER[\"World Geodetic System 1984 (G1762)\"],\n            MEMBER[\"World Geodetic System 1984 (G2139)\"],\n            MEMBER[\"World Geodetic System 1984 (G2296)\"],\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]],\n            ENSEMBLEACCURACY[2.0]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4326]],\n    CONVERSION[\"Popular Visualisation Pseudo-Mercator\",\n        METHOD[\"Popular Visualisation Pseudo Mercator\",\n            ID[\"EPSG\",1024]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"False easting\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Web mapping and visualisation.\"],\n        AREA[\"World between 85.06°S and 85.06°N.\"],\n        BBOX[-85.06,-180,85.06,180]],\n    ID[\"EPSG\",3857]]\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset? 223\n- How many census tracts? 3445\n- What coordinate reference system is each dataset in?\nhospitals is in WGS 84, pa_tracts is in NAD83, and pa_counties is in WGS 84 / Pseudo-Mercator.\n\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\npa_demographic <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  year = 2022,\n  survey = \"acs5\",\n  output = \"wide\",\n  variables = c(\n    # Total population\n    totpop = \"B01003_001\",\n    \n    # Median household income\n    medinc = \"B19013_001\",\n    \n    # Age 65+ (male)\n    m65_66 = \"B01001_020\",\n    m67_69 = \"B01001_021\",\n    m70_74 = \"B01001_022\",\n    m75_79 = \"B01001_023\",\n    m80_84 = \"B01001_024\",\n    m85p   = \"B01001_025\",\n    \n    # Age 65+ (female)\n    f65_66 = \"B01001_044\",\n    f67_69 = \"B01001_045\",\n    f70_74 = \"B01001_046\",\n    f75_79 = \"B01001_047\",\n    f80_84 = \"B01001_048\",\n    f85p   = \"B01001_049\"\n  )\n)\n\n# Create total 65+ column\npa_demographic <- pa_demographic %>%\n  mutate(\n    elderlyE = \n       m65_66E + m67_69E + m70_74E + m75_79E + m80_84E + m85pE +\n      f65_66E + f67_69E + f70_74E + f75_79E + f80_84E + f85pE\n  ) \n\n# Drop unnecessary columns\npa_demographic <- pa_demographic[,-c(7:30)]\n  \n# Join to tract boundaries\ntract_with_data <- pa_tracts %>%\n  left_join(pa_demographic, by = \"GEOID\")\n\n# Answer the question\nsum(is.na(tract_with_data$medincE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 62\n```\n\n\n:::\n\n```{.r .cell-code}\n# Answer the question\nmedinc_PA_tracts = median(tract_with_data$medincE, na.rm = TRUE)\n```\n:::\n\n\n**Questions to answer:**\n- What year of ACS data are you using? 2022\n- How many tracts have missing income data? 62\n- What is the median income across all PA census tracts? 70188\n\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\n# Add a new column pct_elderly to tract_with_data\ntract_with_data <- tract_with_data %>%\n  mutate(\n    pct_elderly = round(elderlyE / totpopE * 100, 1)\n  )\n\n# Define low-income and high elderly thresholds\nincome_cutoff <- quantile(tract_with_data$medincE, 0.25, na.rm = TRUE)\nelderly_cutoff <- quantile(tract_with_data$pct_elderly, 0.75, na.rm = TRUE)\n\n# Define vulnerable population with medinc lower than income_cutoff and pct_elderly higher than elderly_cutoff\n# Flag vulnerability\ntract_with_data <- tract_with_data %>%\n  mutate(\n    vulnerable = medincE <= income_cutoff &\n                 pct_elderly >= elderly_cutoff\n  )\n\n# Filter vulnerable tracts\nvulterable_tract <- tract_with_data %>%\n  filter(vulnerable)\n\n# Summary\ntract_with_data %>%\n  summarise(\n    total_tracts = n(),\n    vulnerable_tracts = sum(vulnerable, na.rm = TRUE),\n    pct_vulnerable = round(mean(vulnerable, na.rm = TRUE) * 100, 2) # vulnerable is logical, mean(vulnerable) equals to #TRUE / total rows\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 3 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -80.51989 ymin: 39.7198 xmax: -74.68952 ymax: 42.26986\nGeodetic CRS:  NAD83\n  total_tracts vulnerable_tracts pct_vulnerable                       geometry\n1         3445               166           4.87 POLYGON ((-76.2398 39.7213,...\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why? 55924; Lowest quantile of median income among all PA census tracts.\n- What elderly population threshold did you choose and why? 23.1%; Highest quantile of percentage of elderly among all PA census tracts.\n- How many tracts meet your vulnerability criteria? 166\n- What percentage of PA census tracts are considered vulnerable by your definition? 4.87%\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\n# NAD83 / UTM Zone 18N, PA lies almost entirely inside UTM Zone 18, units = meters\ntract_with_data <- st_transform(tract_with_data, 26918)\nhospitals <- st_transform(hospitals, 26918)\n\n# Calculate distance from each tract centroid to nearest hospital\n# Create tract centroids\ntract_centroids <- st_centroid(tract_with_data)\n\n# Find nearest hospital index\nnearest_index <- st_nearest_feature(tract_centroids, hospitals)\n\n# Compute distance (m)\nnearest_distance <- st_distance(\n  tract_centroids,\n  hospitals[nearest_index, ],\n  by_element = TRUE\n)\n\n# Convert to miles, 1 mile = 1609.34 meters\ntract_with_data$dist_to_hospital_miles <-\n  round(as.numeric(nearest_distance) / 1609.34, 2)\n\n# Answer the question\n# Average distance in mile\ntract_with_data %>%\n  filter(vulnerable) %>%\n  summarise(\n    avg_distance = round(mean(dist_to_hospital_miles, na.rm = TRUE), 2)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 1 field\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 35702.37 ymin: 4405400 xmax: 499540.6 ymax: 4676929\nProjected CRS: NAD83 / UTM zone 18N\n  avg_distance                       geometry\n1         4.72 MULTIPOLYGON (((83439.9 443...\n```\n\n\n:::\n\n```{.r .cell-code}\n# Maximum distance in mile\ntract_with_data %>%\n  filter(vulnerable) %>%\n  summarise(\n    max_distance = max(dist_to_hospital_miles, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 1 field\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 35702.37 ymin: 4405400 xmax: 499540.6 ymax: 4676929\nProjected CRS: NAD83 / UTM zone 18N\n  max_distance                       geometry\n1        19.16 MULTIPOLYGON (((83439.9 443...\n```\n\n\n:::\n\n```{.r .cell-code}\n# Filter\ntract_with_data %>%\n  filter(vulnerable & dist_to_hospital_miles > 15) %>%\n  summarise(\n    vulnerable_over_15_miles = n()\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 1 field\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 40399.02 ymin: 4460518 xmax: 467793.4 ymax: 4637703\nProjected CRS: NAD83 / UTM zone 18N\n  vulnerable_over_15_miles                       geometry\n1                        9 MULTIPOLYGON (((267600.2 44...\n```\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\n**Questions to answer:**\n- What is the average distance to the nearest hospital for vulnerable tracts? 4.72 miles\n- What is the maximum distance? 19.16 miles\n- How many vulnerable tracts are more than 15 miles from the nearest hospital? 9\n\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\ntract_with_data <- tract_with_data %>%\n  mutate(\n    underserved = vulnerable & dist_to_hospital_miles > 15\n  )\n\n# Answer the question\n# Number of underserved tracts\ntract_with_data %>%\n  summarise(\n    underserved_tracts = sum(underserved, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 1 field\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 26826.63 ymin: 4397195 xmax: 525968.1 ymax: 4690730\nProjected CRS: NAD83 / UTM zone 18N\n  underserved_tracts                       geometry\n1                  9 POLYGON ((64095.69 4409209,...\n```\n\n\n:::\n\n```{.r .cell-code}\n# % of vulnerable tracts that is underserved\ntract_with_data %>%\n  summarise(\n    total_vulnerable = sum(vulnerable, na.rm = TRUE),\n    underserved = sum(underserved, na.rm = TRUE),\n    pct_underserved = round(\n      underserved / total_vulnerable * 100,\n      2\n    )\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 3 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 26826.63 ymin: 4397195 xmax: 525968.1 ymax: 4690730\nProjected CRS: NAD83 / UTM zone 18N\n  total_vulnerable underserved pct_underserved                       geometry\n1              166           9            5.42 POLYGON ((64095.69 4409209,...\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many tracts are underserved? 9\n- What percentage of vulnerable tracts are underserved? 5.42%\n- Does this surprise you? Why or why not? Yes. Only a very low percentage of vulnerable tracts are underserved by hospitals.This suggests that while vulnerable tracts exist, most are not geographically isolated from hospital access. Vulnerability may be driven more by socioeconomic conditions than physical distance.\n\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\n\n\n# Aggregate statistics by county\n```\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\n- Which counties have the most vulnerable people living far from hospitals?\n- Are there any patterns in where underserved counties are located?\n\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\n```\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\n```\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\n```\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\n```\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/). \n\n**Note these are just loose suggestions to spark ideas - follow or make your own as the data permits and as your ideas evolve. This analysis should include bringing in your own dataset, ensuring the projection/CRS of your layers align and are appropriate for the analysis (not lat/long or geodetic coordinate systems). The analysis portion should include some combination of spatial and attribute operations to answer a relatively straightforward question**\n\n---\n\n#### Education & Youth Services\n\n**Option A: Educational Desert Analysis**\n- **Data:** Schools, Libraries, Recreation Centers, Census tracts (child population)\n- **Question:** \"Which neighborhoods lack adequate educational infrastructure for children?\"\n- **Operations:** Buffer schools/libraries (0.5 mile walking distance), identify coverage gaps, overlay with child population density\n- **Policy relevance:** School district planning, library placement, after-school program siting\n\n**Option B: School Safety Zones**\n- **Data:** Schools, Crime Incidents, Bike Network\n- **Question:** \"Are school zones safe for walking/biking, or are they crime hotspots?\"\n- **Operations:** Buffer schools (1000ft safety zone), spatial join with crime incidents, assess bike infrastructure coverage\n- **Policy relevance:** Safe Routes to School programs, crossing guard placement\n\n---\n\n#### Environmental Justice\n\n**Option C: Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n---\n\n#### Public Safety & Justice\n\n**Option D: Crime & Community Resources**\n- **Data:** Crime Incidents, Recreation Centers, Libraries, Street Lights\n- **Question:** \"Are high-crime areas underserved by community resources?\"\n- **Operations:** Aggregate crime counts to census tracts or neighborhoods, count community resources per area, spatial correlation analysis\n- **Policy relevance:** Community investment, violence prevention strategies\n---\n\n#### Infrastructure & Services\n\n**Option E: Polling Place Accessibility**\n- **Data:** Polling Places, SEPTA stops, Census tracts (elderly population, disability rates)\n- **Question:** \"Are polling places accessible for elderly and disabled voters?\"\n- **Operations:** Buffer polling places and transit stops, identify vulnerable populations, find areas lacking access\n- **Policy relevance:** Voting rights, election infrastructure, ADA compliance\n\n---\n\n#### Health & Wellness\n\n**Option F: Recreation & Population Health**\n- **Data:** Recreation Centers, Playgrounds, Parks, Census tracts (demographics)\n- **Question:** \"Is lack of recreation access associated with vulnerable populations?\"\n- **Operations:** Calculate recreation facilities per capita by neighborhood, buffer facilities for walking access, overlay with demographic indicators\n- **Policy relevance:** Public health investment, recreation programming, obesity prevention\n\n---\n\n#### Emergency Services\n\n**Option G: EMS Response Coverage**\n- **Data:** Fire Stations, EMS stations, Population density, High-rise buildings\n- **Question:** \"Are population-dense areas adequately covered by emergency services?\"\n- **Operations:** Create service area buffers (5-minute drive = ~2 miles), assess population coverage, identify gaps in high-density areas\n- **Policy relevance:** Emergency preparedness, station siting decisions\n\n---\n\n#### Arts & Culture\n\n**Option H: Cultural Asset Distribution**\n- **Data:** Public Art, Museums, Historic sites/markers, Neighborhoods\n- **Question:** \"Do all neighborhoods have equitable access to cultural amenities?\"\n- **Operations:** Count cultural assets per neighborhood, normalize by population, compare distribution across demographic groups\n- **Policy relevance:** Cultural equity, tourism, quality of life, neighborhood identity\n\n---\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n- Most datasets available as GeoJSON, Shapefile, or CSV with coordinates\n- Always check the Metadata for a data dictionary of the fields.\n\n**Additional Sources:**\n- **Pennsylvania Open Data:** https://data.pa.gov/\n- **Census Bureau (via tidycensus):** Demographics, economic indicators, commute patterns\n- **TIGER/Line (via tigris):** Geographic boundaries\n\n### Recommended Starting Points\n\n**If you're feeling confident:** Choose an advanced challenge with multiple data layers. \n**If you are a beginner, choose something more manageable that helps you understand the basics**\n\n\n**If you have a different idea:** Propose your own question! Just make sure:\n- You can access the spatial data\n- You can perform at least 2 spatial operations\n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\n```\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\n- What is the data source and date?\n- How many features does it contain?\n- What CRS is it in? Did you need to transform it?\n\n---\n\n2. **Pose a research question**\n\nWrite a clear research statement that your analysis will answer.\n\n**Examples:**\n- \"Do vulnerable tracts have adequate public transit access to hospitals?\"\n- \"Are EMS stations appropriately located near vulnerable populations?\"\n- \"Do areas with low vehicle access have worse hospital access?\"\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\n```\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\n[Write your findings here]\n\n\n## Finally - A few comments about your incorporation of feedback!\nTake a few moments to clean up your markdown document and then write a line or two or three about how you may have incorporated feedback that you recieved after your first assignment. \n\n---\n\n## Submission Requirements\n\n**What to submit:**\n\n1. **Rendered HTML document posted to your course portfolio** with all code, outputs, maps, and text\n   - Use `embed-resources: true` in YAML so it's a single file\n   - All code should run without errors\n   - All maps and charts should display correctly\n2. Submit the correct and working links of your assignment on Canvas\n\n---\n\n",
    "supporting": [
      "lab2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}